# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_DUT.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window_DUT(object):
    def setupUi(self, Window_DUT):
        Window_DUT.setObjectName("Window_DUT")
        Window_DUT.resize(1070, 578)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon/dut.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window_DUT.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Window_DUT)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_DUT = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_DUT.setGeometry(QtCore.QRect(220, 110, 831, 331))
        self.tabWidget_DUT.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget_DUT.setToolTip("")
        self.tabWidget_DUT.setAutoFillBackground(False)
        self.tabWidget_DUT.setStyleSheet("")
        self.tabWidget_DUT.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_DUT.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_DUT.setTabBarAutoHide(False)
        self.tabWidget_DUT.setObjectName("tabWidget_DUT")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 30, 661, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_DUTfacturer = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_DUTfacturer.setObjectName("lineEdit_DUTfacturer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_DUTfacturer)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_DUTSN = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_DUTSN.setObjectName("lineEdit_DUTSN")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_DUTSN)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_HWrev = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_HWrev.setObjectName("lineEdit_HWrev")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_HWrev)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_SWrev = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_SWrev.setObjectName("lineEdit_SWrev")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_SWrev)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_DUTIMEI = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_DUTIMEI.setObjectName("lineEdit_DUTIMEI")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_DUTIMEI)
        self.label_3.raise_()
        self.label_2.raise_()
        self.lineEdit_DUTSN.raise_()
        self.label_4.raise_()
        self.lineEdit_HWrev.raise_()
        self.label_5.raise_()
        self.lineEdit_SWrev.raise_()
        self.label_6.raise_()
        self.lineEdit_DUTIMEI.raise_()
        self.lineEdit_DUTfacturer.raise_()
        self.tabWidget_DUT.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 661, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEdit_MaxRegTime = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_MaxRegTime.setObjectName("lineEdit_MaxRegTime")
        self.horizontalLayout_4.addWidget(self.lineEdit_MaxRegTime)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(71, 221, 80, 16))
        self.label_26.setObjectName("label_26")
        self.comboBox_Nosigntool = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_Nosigntool.setGeometry(QtCore.QRect(159, 220, 62, 21))
        self.comboBox_Nosigntool.setObjectName("comboBox_Nosigntool")
        self.comboBox_Nosigntool.addItem("")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(200, 150, 32, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_COMPort = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_COMPort.setGeometry(QtCore.QRect(239, 150, 171, 21))
        self.lineEdit_COMPort.setObjectName("lineEdit_COMPort")
        self.radioButton_ManunalMode = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_ManunalMode.setGeometry(QtCore.QRect(47, 71, 16, 16))
        self.radioButton_ManunalMode.setText("")
        self.radioButton_ManunalMode.setObjectName("radioButton_ManunalMode")
        self.radioButton_PowerMode = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_PowerMode.setGeometry(QtCore.QRect(47, 110, 16, 16))
        self.radioButton_PowerMode.setText("")
        self.radioButton_PowerMode.setObjectName("radioButton_PowerMode")
        self.radioButton_ATCMD = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_ATCMD.setGeometry(QtCore.QRect(48, 150, 16, 16))
        self.radioButton_ATCMD.setText("")
        self.radioButton_ATCMD.setObjectName("radioButton_ATCMD")
        self.radioButton_NOSIGN = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_NOSIGN.setGeometry(QtCore.QRect(48, 221, 16, 16))
        self.radioButton_NOSIGN.setText("")
        self.radioButton_NOSIGN.setObjectName("radioButton_NOSIGN")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(70, 71, 88, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(70, 110, 144, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(71, 150, 120, 16))
        self.label_11.setObjectName("label_11")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(72, 261, 80, 16))
        self.label_28.setObjectName("label_28")
        self.radioButton_SIGN = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_SIGN.setGeometry(QtCore.QRect(49, 261, 16, 16))
        self.radioButton_SIGN.setText("")
        self.radioButton_SIGN.setObjectName("radioButton_SIGN")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 601, 131))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 190, 601, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_COMPort_QRCT = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_COMPort_QRCT.setGeometry(QtCore.QRect(250, 30, 131, 21))
        self.lineEdit_COMPort_QRCT.setObjectName("lineEdit_COMPort_QRCT")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(211, 30, 32, 16))
        self.label_29.setObjectName("label_29")
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.layoutWidget.raise_()
        self.label_26.raise_()
        self.comboBox_Nosigntool.raise_()
        self.label_27.raise_()
        self.lineEdit_COMPort.raise_()
        self.radioButton_ManunalMode.raise_()
        self.radioButton_PowerMode.raise_()
        self.radioButton_ATCMD.raise_()
        self.radioButton_NOSIGN.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_28.raise_()
        self.radioButton_SIGN.raise_()
        self.tabWidget_DUT.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 10, 611, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEdit_HighVolt = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_HighVolt.setObjectName("lineEdit_HighVolt")
        self.gridLayout.addWidget(self.lineEdit_HighVolt, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_NorVolt = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_NorVolt.setObjectName("lineEdit_NorVolt")
        self.gridLayout.addWidget(self.lineEdit_NorVolt, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineEdit_LowVolt = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_LowVolt.setObjectName("lineEdit_LowVolt")
        self.gridLayout.addWidget(self.lineEdit_LowVolt, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.lineEdit_MaxCurrent = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_MaxCurrent.setObjectName("lineEdit_MaxCurrent")
        self.gridLayout.addWidget(self.lineEdit_MaxCurrent, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.lineEdit_HighTemp = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_HighTemp.setObjectName("lineEdit_HighTemp")
        self.gridLayout.addWidget(self.lineEdit_HighTemp, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 5, 0, 1, 1)
        self.lineEdit_NorTemp = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_NorTemp.setObjectName("lineEdit_NorTemp")
        self.gridLayout.addWidget(self.lineEdit_NorTemp, 5, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 6, 0, 1, 1)
        self.lineEdit_LowTemp = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_LowTemp.setObjectName("lineEdit_LowTemp")
        self.gridLayout.addWidget(self.lineEdit_LowTemp, 6, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 2, 1, 1)
        self.tabWidget_DUT.addTab(self.tab_3, "")
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setGeometry(QtCore.QRect(860, 490, 93, 28))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.pushButton_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(960, 490, 93, 28))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 43, 395, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_NewDUT = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_NewDUT.setObjectName("pushButton_NewDUT")
        self.horizontalLayout.addWidget(self.pushButton_NewDUT)
        self.pushButton_Saveas = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_Saveas.setObjectName("pushButton_Saveas")
        self.horizontalLayout.addWidget(self.pushButton_Saveas)
        self.pushButton_ActDUT = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_ActDUT.setObjectName("pushButton_ActDUT")
        self.horizontalLayout.addWidget(self.pushButton_ActDUT)
        self.pushButton_RemoveDUT = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_RemoveDUT.setObjectName("pushButton_RemoveDUT")
        self.horizontalLayout.addWidget(self.pushButton_RemoveDUT)
        self.pushButton_updata = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_updata.setGeometry(QtCore.QRect(220, 450, 831, 28))
        self.pushButton_updata.setObjectName("pushButton_updata")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 111, 112, 16))
        self.label.setObjectName("label")
        self.listWidget_DUT = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_DUT.setGeometry(QtCore.QRect(21, 133, 179, 341))
        self.listWidget_DUT.setObjectName("listWidget_DUT")
        Window_DUT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_DUT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        Window_DUT.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window_DUT)
        self.statusbar.setObjectName("statusbar")
        Window_DUT.setStatusBar(self.statusbar)

        self.retranslateUi(Window_DUT)
        self.tabWidget_DUT.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Window_DUT)

    def retranslateUi(self, Window_DUT):
        _translate = QtCore.QCoreApplication.translate
        Window_DUT.setWindowTitle(_translate("Window_DUT", "DUT Editor"))
        self.tabWidget_DUT.setWhatsThis(_translate("Window_DUT", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("Window_DUT", "DUT Manufacturer:"))
        self.label_2.setText(_translate("Window_DUT", "DUT Serial Number:"))
        self.label_4.setText(_translate("Window_DUT", "DUT Hardware Revision:"))
        self.label_5.setText(_translate("Window_DUT", "DUT Software Revision:"))
        self.label_6.setText(_translate("Window_DUT", "DUT IMEI:"))
        self.tabWidget_DUT.setTabText(self.tabWidget_DUT.indexOf(self.tab), _translate("Window_DUT", "DUT Parameters"))
        self.label_7.setText(_translate("Window_DUT", "Maximum Registration Time:"))
        self.label_8.setText(_translate("Window_DUT", "[30s:600s]"))
        self.label_26.setText(_translate("Window_DUT", "NonSigning"))
        self.comboBox_Nosigntool.setItemText(0, _translate("Window_DUT", "QRCT"))
        self.label_27.setText(_translate("Window_DUT", "COM:"))
        self.label_9.setText(_translate("Window_DUT", "Manual Mode"))
        self.label_10.setText(_translate("Window_DUT", "Power Cycling Mode"))
        self.label_11.setText(_translate("Window_DUT", "AT Command Mode"))
        self.label_28.setText(_translate("Window_DUT", "Signing"))
        self.groupBox.setTitle(_translate("Window_DUT", "Cellular Network"))
        self.groupBox_3.setTitle(_translate("Window_DUT", "Un-Cellular Network"))
        self.label_29.setText(_translate("Window_DUT", "COM:"))
        self.tabWidget_DUT.setTabText(self.tabWidget_DUT.indexOf(self.tab_2), _translate("Window_DUT", "Automation"))
        self.label_12.setText(_translate("Window_DUT", "Voltage High:"))
        self.label_19.setText(_translate("Window_DUT", "V"))
        self.label_13.setText(_translate("Window_DUT", "Voltage Normal:"))
        self.label_20.setText(_translate("Window_DUT", "V"))
        self.label_14.setText(_translate("Window_DUT", "Voltage Low:"))
        self.label_21.setText(_translate("Window_DUT", "V"))
        self.label_15.setText(_translate("Window_DUT", "Current Max:"))
        self.label_22.setText(_translate("Window_DUT", "A"))
        self.label_16.setText(_translate("Window_DUT", "Temperature High:"))
        self.label_23.setText(_translate("Window_DUT", "℃"))
        self.label_17.setText(_translate("Window_DUT", "Temperature Normal:"))
        self.label_24.setText(_translate("Window_DUT", "℃"))
        self.label_18.setText(_translate("Window_DUT", "Temperature Low:"))
        self.label_25.setText(_translate("Window_DUT", "℃"))
        self.tabWidget_DUT.setTabText(self.tabWidget_DUT.indexOf(self.tab_3), _translate("Window_DUT", "Test Environment"))
        self.pushButton_Save.setText(_translate("Window_DUT", "Save"))
        self.pushButton_Cancel.setText(_translate("Window_DUT", "Cancel"))
        self.pushButton_NewDUT.setText(_translate("Window_DUT", "New DUT"))
        self.pushButton_Saveas.setText(_translate("Window_DUT", "Save as…"))
        self.pushButton_ActDUT.setText(_translate("Window_DUT", "Active DUT"))
        self.pushButton_RemoveDUT.setText(_translate("Window_DUT", "Remove DUT"))
        self.pushButton_updata.setText(_translate("Window_DUT", "Updata DUT Config"))
        self.label.setText(_translate("Window_DUT", "Available DUTs"))

