# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_itemparam.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window_itemparam(object):
    def setupUi(self, Window_itemparam):
        Window_itemparam.setObjectName("Window_itemparam")
        Window_itemparam.setWindowModality(QtCore.Qt.NonModal)
        Window_itemparam.resize(1019, 607)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon/seq.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window_itemparam.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Window_itemparam)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget_itemconfig = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(7)
        self.tableWidget_itemconfig.setFont(font)
        self.tableWidget_itemconfig.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget_itemconfig.setObjectName("tableWidget_itemconfig")
        self.tableWidget_itemconfig.setColumnCount(2)
        self.tableWidget_itemconfig.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemconfig.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemconfig.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget_itemconfig)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tableWidget_itemlimit = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(7)
        self.tableWidget_itemlimit.setFont(font)
        self.tableWidget_itemlimit.setObjectName("tableWidget_itemlimit")
        self.tableWidget_itemlimit.setColumnCount(3)
        self.tableWidget_itemlimit.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemlimit.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemlimit.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_itemlimit.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.tableWidget_itemlimit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setStyleSheet("border:2px solid yellow;")
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")
        self.horizontalLayout_2.addWidget(self.label_info)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.verticalLayout_3.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout_3.addWidget(self.pushButton_cancel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem2)
        Window_itemparam.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_itemparam)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 26))
        self.menubar.setObjectName("menubar")
        Window_itemparam.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window_itemparam)
        self.statusbar.setObjectName("statusbar")
        Window_itemparam.setStatusBar(self.statusbar)

        self.retranslateUi(Window_itemparam)
        QtCore.QMetaObject.connectSlotsByName(Window_itemparam)

    def retranslateUi(self, Window_itemparam):
        _translate = QtCore.QCoreApplication.translate
        Window_itemparam.setWindowTitle(_translate("Window_itemparam", "Item Config"))
        self.label.setText(_translate("Window_itemparam", "Item Config:"))
        item = self.tableWidget_itemconfig.horizontalHeaderItem(0)
        item.setText(_translate("Window_itemparam", "Param Name"))
        item = self.tableWidget_itemconfig.horizontalHeaderItem(1)
        item.setText(_translate("Window_itemparam", "Param Value"))
        self.label_2.setText(_translate("Window_itemparam", "Item Limit:"))
        item = self.tableWidget_itemlimit.horizontalHeaderItem(0)
        item.setText(_translate("Window_itemparam", "Limit Name"))
        item = self.tableWidget_itemlimit.horizontalHeaderItem(1)
        item.setText(_translate("Window_itemparam", "Low Limit"))
        item = self.tableWidget_itemlimit.horizontalHeaderItem(2)
        item.setText(_translate("Window_itemparam", "High Limit"))
        self.label_3.setText(_translate("Window_itemparam", "Remark:"))
        self.pushButton_ok.setText(_translate("Window_itemparam", "OK"))
        self.pushButton_cancel.setText(_translate("Window_itemparam", "Cancel"))

