# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_report_tool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window_report_tool(object):
    def setupUi(self, Window_report_tool):
        Window_report_tool.setObjectName("Window_report_tool")
        Window_report_tool.resize(1029, 695)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon/rep2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window_report_tool.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Window_report_tool)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 380, 277))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_objectname = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_objectname.setObjectName("lineEdit_objectname")
        self.gridLayout.addWidget(self.lineEdit_objectname, 1, 2, 1, 1)
        self.comboBox_testedby = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_testedby.setObjectName("comboBox_testedby")
        self.comboBox_testedby.addItem("")
        self.comboBox_testedby.setItemText(0, "")
        self.comboBox_testedby.addItem("")
        self.comboBox_testedby.addItem("")
        self.comboBox_testedby.addItem("")
        self.comboBox_testedby.addItem("")
        self.comboBox_testedby.addItem("")
        self.comboBox_testedby.addItem("")
        self.comboBox_testedby.addItem("")
        self.gridLayout.addWidget(self.comboBox_testedby, 2, 2, 1, 1)
        self.lineEdit_grantNo = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_grantNo.setObjectName("lineEdit_grantNo")
        self.gridLayout.addWidget(self.lineEdit_grantNo, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.dateEdit_receipt = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_receipt.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_receipt.setObjectName("dateEdit_receipt")
        self.gridLayout.addWidget(self.dateEdit_receipt, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.lineEdit_brand = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_brand.setObjectName("lineEdit_brand")
        self.gridLayout.addWidget(self.lineEdit_brand, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_producttype = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_producttype.setObjectName("lineEdit_producttype")
        self.gridLayout.addWidget(self.lineEdit_producttype, 8, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateEdit_teststart = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_teststart.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_teststart.setObjectName("dateEdit_teststart")
        self.horizontalLayout.addWidget(self.dateEdit_teststart)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.dateEdit_teststop = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_teststop.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_teststop.setObjectName("dateEdit_teststop")
        self.horizontalLayout.addWidget(self.dateEdit_teststop)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 2)
        self.dateEdit_issue = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_issue.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_issue.setObjectName("dateEdit_issue")
        self.gridLayout.addWidget(self.dateEdit_issue, 7, 2, 1, 1)
        self.lineEdit_reportNo = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_reportNo.setObjectName("lineEdit_reportNo")
        self.gridLayout.addWidget(self.lineEdit_reportNo, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 0, 1, 1)
        self.lineEdit_brandaddr = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_brandaddr.setObjectName("lineEdit_brandaddr")
        self.gridLayout.addWidget(self.lineEdit_brandaddr, 9, 2, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(440, 30, 388, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_hwversion = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_hwversion.setObjectName("lineEdit_hwversion")
        self.gridLayout_3.addWidget(self.lineEdit_hwversion, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.lineEdit_swversion = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_swversion.setObjectName("lineEdit_swversion")
        self.gridLayout_3.addWidget(self.lineEdit_swversion, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 971, 65))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_datesource = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_datesource.setObjectName("lineEdit_datesource")
        self.gridLayout_2.addWidget(self.lineEdit_datesource, 0, 1, 1, 1)
        self.pushButton_scandatesource = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_scandatesource.setObjectName("pushButton_scandatesource")
        self.gridLayout_2.addWidget(self.pushButton_scandatesource, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_reportadd = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_reportadd.setObjectName("lineEdit_reportadd")
        self.gridLayout_2.addWidget(self.lineEdit_reportadd, 1, 1, 1, 1)
        self.pushButton_scanreportadd = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_scanreportadd.setObjectName("pushButton_scanreportadd")
        self.gridLayout_2.addWidget(self.pushButton_scanreportadd, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_gsmfcc = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_gsmfcc.setObjectName("checkBox_gsmfcc")
        self.horizontalLayout_2.addWidget(self.checkBox_gsmfcc)
        self.checkBox_wcdmafcc = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_wcdmafcc.setObjectName("checkBox_wcdmafcc")
        self.horizontalLayout_2.addWidget(self.checkBox_wcdmafcc)
        self.checkBox_ltefcc = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ltefcc.sizePolicy().hasHeightForWidth())
        self.checkBox_ltefcc.setSizePolicy(sizePolicy)
        self.checkBox_ltefcc.setMinimumSize(QtCore.QSize(0, 10))
        self.checkBox_ltefcc.setMaximumSize(QtCore.QSize(16777215, 30))
        self.checkBox_ltefcc.setObjectName("checkBox_ltefcc")
        self.horizontalLayout_2.addWidget(self.checkBox_ltefcc)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(600, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton_creatreport = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_creatreport.setFont(font)
        self.pushButton_creatreport.setObjectName("pushButton_creatreport")
        self.verticalLayout.addWidget(self.pushButton_creatreport)
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.layoutWidget.raise_()
        self.groupBox.raise_()
        Window_report_tool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_report_tool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1029, 26))
        self.menubar.setObjectName("menubar")
        Window_report_tool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window_report_tool)
        self.statusbar.setObjectName("statusbar")
        Window_report_tool.setStatusBar(self.statusbar)

        self.retranslateUi(Window_report_tool)
        QtCore.QMetaObject.connectSlotsByName(Window_report_tool)

    def retranslateUi(self, Window_report_tool):
        _translate = QtCore.QCoreApplication.translate
        Window_report_tool.setWindowTitle(_translate("Window_report_tool", "Report Tool"))
        self.groupBox.setTitle(_translate("Window_report_tool", "Information of Object:"))
        self.label.setText(_translate("Window_report_tool", "Tested by:"))
        self.label_3.setText(_translate("Window_report_tool", "Grant No.:"))
        self.comboBox_testedby.setItemText(1, _translate("Window_report_tool", "王亮"))
        self.comboBox_testedby.setItemText(2, _translate("Window_report_tool", "鲁芬"))
        self.comboBox_testedby.setItemText(3, _translate("Window_report_tool", "郑红艳"))
        self.comboBox_testedby.setItemText(4, _translate("Window_report_tool", "陈燕"))
        self.comboBox_testedby.setItemText(5, _translate("Window_report_tool", "朱保华"))
        self.comboBox_testedby.setItemText(6, _translate("Window_report_tool", "李兴朗"))
        self.comboBox_testedby.setItemText(7, _translate("Window_report_tool", "王莹"))
        self.label_7.setText(_translate("Window_report_tool", "Report No.:"))
        self.label_4.setText(_translate("Window_report_tool", "Date of Receipt:"))
        self.dateEdit_receipt.setDisplayFormat(_translate("Window_report_tool", "yyyy/MM/dd"))
        self.label_2.setText(_translate("Window_report_tool", "Object Name:"))
        self.label_11.setText(_translate("Window_report_tool", "Product Type:"))
        self.label_10.setText(_translate("Window_report_tool", "Brand:"))
        self.lineEdit_producttype.setText(_translate("Window_report_tool", "Smart Phone"))
        self.dateEdit_teststart.setDisplayFormat(_translate("Window_report_tool", "yyyy/MM/dd"))
        self.dateEdit_teststop.setDisplayFormat(_translate("Window_report_tool", "yyyy/MM/dd"))
        self.label_6.setText(_translate("Window_report_tool", "Date of Issue:"))
        self.dateEdit_issue.setDisplayFormat(_translate("Window_report_tool", "yyyy/MM/dd"))
        self.lineEdit_reportNo.setText(_translate("Window_report_tool", "RYYYYMM***"))
        self.label_5.setText(_translate("Window_report_tool", "Date of Test:"))
        self.label_12.setText(_translate("Window_report_tool", "Brand Address:"))
        self.label_17.setText(_translate("Window_report_tool", "Software Version:"))
        self.label_19.setText(_translate("Window_report_tool", "Hardware Version:"))
        self.groupBox_2.setTitle(_translate("Window_report_tool", "Information of Date:"))
        self.label_8.setText(_translate("Window_report_tool", "Data Source:"))
        self.pushButton_scandatesource.setText(_translate("Window_report_tool", "Scan"))
        self.label_9.setText(_translate("Window_report_tool", "Report Address:"))
        self.pushButton_scanreportadd.setText(_translate("Window_report_tool", "Scan"))
        self.checkBox_gsmfcc.setText(_translate("Window_report_tool", "GSM FCC"))
        self.checkBox_wcdmafcc.setText(_translate("Window_report_tool", "WCDMA FCC"))
        self.checkBox_ltefcc.setText(_translate("Window_report_tool", "LTE FCC"))
        self.pushButton_creatreport.setText(_translate("Window_report_tool", "Creat Report as Word"))
        self.pushButton_cancel.setText(_translate("Window_report_tool", "Cancel"))

