# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_test_seq.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window_testseq(object):
    def setupUi(self, Window_testseq):
        Window_testseq.setObjectName("Window_testseq")
        Window_testseq.resize(1049, 606)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon/seq.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window_testseq.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Window_testseq)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.listWidget_testseq = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_testseq.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_testseq.setObjectName("listWidget_testseq")
        self.verticalLayout_4.addWidget(self.listWidget_testseq)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_addcase = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addcase.setObjectName("pushButton_addcase")
        self.verticalLayout_2.addWidget(self.pushButton_addcase)
        self.pushButton_editcase = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_editcase.setObjectName("pushButton_editcase")
        self.verticalLayout_2.addWidget(self.pushButton_editcase)
        self.pushButton_copy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.verticalLayout_2.addWidget(self.pushButton_copy)
        self.pushButton_removecase = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_removecase.setObjectName("pushButton_removecase")
        self.verticalLayout_2.addWidget(self.pushButton_removecase)
        self.pushButton_up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_up.setObjectName("pushButton_up")
        self.verticalLayout_2.addWidget(self.pushButton_up)
        self.pushButton_down = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_down.setObjectName("pushButton_down")
        self.verticalLayout_2.addWidget(self.pushButton_down)
        self.pushButton_enableall = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enableall.setObjectName("pushButton_enableall")
        self.verticalLayout_2.addWidget(self.pushButton_enableall)
        self.pushButton_disableall = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_disableall.setObjectName("pushButton_disableall")
        self.verticalLayout_2.addWidget(self.pushButton_disableall)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.verticalLayout_3.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout_3.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        Window_testseq.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_testseq)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1049, 26))
        self.menubar.setObjectName("menubar")
        self.menuLoad_Sequence = QtWidgets.QMenu(self.menubar)
        self.menuLoad_Sequence.setObjectName("menuLoad_Sequence")
        self.menuAdd_Sequence = QtWidgets.QMenu(self.menubar)
        self.menuAdd_Sequence.setObjectName("menuAdd_Sequence")
        self.menuSave_Sequence = QtWidgets.QMenu(self.menubar)
        self.menuSave_Sequence.setObjectName("menuSave_Sequence")
        Window_testseq.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window_testseq)
        self.statusbar.setObjectName("statusbar")
        Window_testseq.setStatusBar(self.statusbar)
        self.actionLoadSequence = QtWidgets.QAction(Window_testseq)
        self.actionLoadSequence.setObjectName("actionLoadSequence")
        self.actionAdd_Sequence = QtWidgets.QAction(Window_testseq)
        self.actionAdd_Sequence.setObjectName("actionAdd_Sequence")
        self.actionSave_Sequence = QtWidgets.QAction(Window_testseq)
        self.actionSave_Sequence.setObjectName("actionSave_Sequence")
        self.menuLoad_Sequence.addAction(self.actionLoadSequence)
        self.menuAdd_Sequence.addAction(self.actionAdd_Sequence)
        self.menuSave_Sequence.addAction(self.actionSave_Sequence)
        self.menubar.addAction(self.menuLoad_Sequence.menuAction())
        self.menubar.addAction(self.menuAdd_Sequence.menuAction())
        self.menubar.addAction(self.menuSave_Sequence.menuAction())

        self.retranslateUi(Window_testseq)
        QtCore.QMetaObject.connectSlotsByName(Window_testseq)

    def retranslateUi(self, Window_testseq):
        _translate = QtCore.QCoreApplication.translate
        Window_testseq.setWindowTitle(_translate("Window_testseq", "Test Sequence Editor"))
        self.label.setText(_translate("Window_testseq", "Test Sequence View:"))
        self.pushButton_addcase.setText(_translate("Window_testseq", "Add TestCase"))
        self.pushButton_editcase.setText(_translate("Window_testseq", "Edit TestCase"))
        self.pushButton_copy.setText(_translate("Window_testseq", "Copy TestCase"))
        self.pushButton_removecase.setText(_translate("Window_testseq", "Remove TestCase"))
        self.pushButton_up.setText(_translate("Window_testseq", "Move Up"))
        self.pushButton_down.setText(_translate("Window_testseq", "Move Down"))
        self.pushButton_enableall.setText(_translate("Window_testseq", "Enable All"))
        self.pushButton_disableall.setText(_translate("Window_testseq", "Disable All"))
        self.pushButton_ok.setText(_translate("Window_testseq", "OK"))
        self.pushButton_cancel.setText(_translate("Window_testseq", "Cancel"))
        self.menuLoad_Sequence.setTitle(_translate("Window_testseq", "Load Sequence"))
        self.menuAdd_Sequence.setTitle(_translate("Window_testseq", "Add Sequence"))
        self.menuSave_Sequence.setTitle(_translate("Window_testseq", "Save Sequence"))
        self.actionLoadSequence.setText(_translate("Window_testseq", "LoadSequence"))
        self.actionAdd_Sequence.setText(_translate("Window_testseq", "Add Sequence"))
        self.actionSave_Sequence.setText(_translate("Window_testseq", "Save Sequence"))

