# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_testplan.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window_testplan(object):
    def setupUi(self, Window_testplan):
        Window_testplan.setObjectName("Window_testplan")
        Window_testplan.resize(1100, 672)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./image/icon/seq.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window_testplan.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Window_testplan)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 201, 16))
        self.label_2.setObjectName("label_2")
        self.listWidget_supporteditems = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_supporteditems.setGeometry(QtCore.QRect(20, 100, 351, 361))
        self.listWidget_supporteditems.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidget_supporteditems.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_supporteditems.setObjectName("listWidget_supporteditems")
        self.listWidget_testplan = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_testplan.setGeometry(QtCore.QRect(540, 100, 521, 361))
        self.listWidget_testplan.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_testplan.setObjectName("listWidget_testplan")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 70, 201, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 490, 901, 121))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 301, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_Temp = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_Temp.setObjectName("comboBox_Temp")
        self.comboBox_Temp.addItem("")
        self.comboBox_Temp.addItem("")
        self.comboBox_Temp.addItem("")
        self.gridLayout.addWidget(self.comboBox_Temp, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_Volt = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_Volt.setObjectName("comboBox_Volt")
        self.comboBox_Volt.addItem("")
        self.comboBox_Volt.addItem("")
        self.comboBox_Volt.addItem("")
        self.gridLayout.addWidget(self.comboBox_Volt, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(390, 40, 467, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_temptime = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_temptime.setObjectName("lineEdit_temptime")
        self.horizontalLayout_2.addWidget(self.lineEdit_temptime)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 20, 199, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_loadmodule = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_loadmodule.setObjectName("comboBox_loadmodule")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.setItemText(0, "")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.comboBox_loadmodule.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_loadmodule)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(410, 110, 99, 331))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_add = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.pushButton_add)
        self.pushButton_remove = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.verticalLayout.addWidget(self.pushButton_remove)
        self.pushButton_up = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_up.setObjectName("pushButton_up")
        self.verticalLayout.addWidget(self.pushButton_up)
        self.pushButton_down = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_down.setObjectName("pushButton_down")
        self.verticalLayout.addWidget(self.pushButton_down)
        self.pushButton_enableall = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_enableall.setObjectName("pushButton_enableall")
        self.verticalLayout.addWidget(self.pushButton_enableall)
        self.pushButton_disableall = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_disableall.setObjectName("pushButton_disableall")
        self.verticalLayout.addWidget(self.pushButton_disableall)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(960, 520, 95, 65))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_ok = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.verticalLayout_2.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout_2.addWidget(self.pushButton_cancel)
        self.label_plantitle = QtWidgets.QLabel(self.centralwidget)
        self.label_plantitle.setGeometry(QtCore.QRect(406, 21, 271, 16))
        self.label_plantitle.setText("")
        self.label_plantitle.setObjectName("label_plantitle")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(271, 21, 128, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_plantitle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_plantitle.setGeometry(QtCore.QRect(840, 21, 171, 21))
        self.lineEdit_plantitle.setObjectName("lineEdit_plantitle")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(711, 21, 131, 16))
        self.label_9.setObjectName("label_9")
        Window_testplan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_testplan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 26))
        self.menubar.setObjectName("menubar")
        Window_testplan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window_testplan)
        self.statusbar.setObjectName("statusbar")
        Window_testplan.setStatusBar(self.statusbar)

        self.retranslateUi(Window_testplan)
        QtCore.QMetaObject.connectSlotsByName(Window_testplan)

    def retranslateUi(self, Window_testplan):
        _translate = QtCore.QCoreApplication.translate
        Window_testplan.setWindowTitle(_translate("Window_testplan", "Test Plan Editor"))
        self.label_2.setText(_translate("Window_testplan", "Supported Items:"))
        self.label_3.setText(_translate("Window_testplan", "Test Plan:"))
        self.groupBox.setTitle(_translate("Window_testplan", "Test Condition"))
        self.label_5.setText(_translate("Window_testplan", "Temperature:"))
        self.comboBox_Temp.setItemText(0, _translate("Window_testplan", "NT"))
        self.comboBox_Temp.setItemText(1, _translate("Window_testplan", "HT"))
        self.comboBox_Temp.setItemText(2, _translate("Window_testplan", "LT"))
        self.label_6.setText(_translate("Window_testplan", "Voltage:"))
        self.comboBox_Volt.setItemText(0, _translate("Window_testplan", "NV"))
        self.comboBox_Volt.setItemText(1, _translate("Window_testplan", "HV"))
        self.comboBox_Volt.setItemText(2, _translate("Window_testplan", "LV"))
        self.label_4.setText(_translate("Window_testplan", " Temperature stabilization time:"))
        self.lineEdit_temptime.setText(_translate("Window_testplan", "10"))
        self.label_7.setText(_translate("Window_testplan", "min"))
        self.label.setText(_translate("Window_testplan", "Load Module:"))
        self.comboBox_loadmodule.setItemText(1, _translate("Window_testplan", "GSMFCC"))
        self.comboBox_loadmodule.setItemText(2, _translate("Window_testplan", "WCDMAFCC"))
        self.comboBox_loadmodule.setItemText(3, _translate("Window_testplan", "LTEFCC"))
        self.comboBox_loadmodule.setItemText(4, _translate("Window_testplan", "LTECAFCC"))
        self.comboBox_loadmodule.setItemText(5, _translate("Window_testplan", "BT2FCC"))
        self.comboBox_loadmodule.setItemText(6, _translate("Window_testplan", "BT2CE"))
        self.comboBox_loadmodule.setItemText(7, _translate("Window_testplan", "WLAN_A"))
        self.comboBox_loadmodule.setItemText(8, _translate("Window_testplan", "WLAN_B"))
        self.comboBox_loadmodule.setItemText(9, _translate("Window_testplan", "WLAN_G"))
        self.comboBox_loadmodule.setItemText(10, _translate("Window_testplan", "WLAN_N"))
        self.comboBox_loadmodule.setItemText(11, _translate("Window_testplan", "WLAN_AC"))
        self.pushButton_add.setText(_translate("Window_testplan", "Add to "))
        self.pushButton_remove.setText(_translate("Window_testplan", "Remove"))
        self.pushButton_up.setText(_translate("Window_testplan", "Up"))
        self.pushButton_down.setText(_translate("Window_testplan", "Down"))
        self.pushButton_enableall.setText(_translate("Window_testplan", "Enable All"))
        self.pushButton_disableall.setText(_translate("Window_testplan", "Disable All"))
        self.pushButton_ok.setText(_translate("Window_testplan", "OK"))
        self.pushButton_cancel.setText(_translate("Window_testplan", "Cancel"))
        self.label_8.setText(_translate("Window_testplan", "Test Plan Title:"))
        self.label_9.setText(_translate("Window_testplan", "Addtional Title:"))

